name: Publish
on:
  push:
    branches:
      - main
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  container:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow_ref }}-${{ github.job }}
    permissions:
      contents: read
      packages: write
    steps:
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v4
      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
      - name: Build and publish
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Containerfile
          platforms: |
            linux/amd64
            linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
      - uses: actions/delete-package-versions@v5
        with:
          package-name: sentium
          package-type: container
          min-versions-to-keep: 2
          delete-only-untagged-versions: true
